### ISSUE TITLE
API keys not working?

### ISSUE THREAD

**Issue by dan300** [mannieschumpert/quicktask#2]
I can't seem to set akey bc of this:

[2017-02-01 04:08:40][ERROR: action.script] mkdir: /Users/{username}/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data: No such file or directory
mkdir: /Users/dani/Library/Application Support/Alfred 2/Workflow Data: No such file or directory

I'm not sure why it's looking for Alfred 2.. ?

**Comment by therealscottcarlow** [comment]
@dan300 It's because this needs some modification to work with Alfred 3. workflow.php calls for Alfred 2 directories. Do a find and replace, replacing `Alfred-2` with `Alfred-3`, and replacing `Alfred 2` with `Alfred 3`. After that everything will work like it's supposed to.

**Comment by dan300** [comment]
**Works!**

Thanks @therealscottcarlow I appreciate this a lot! 🙇🏾

**Comment by pawsys** [comment]
@dan300 does it still work for you in Alfred 4?
